---
- name: Identify additional exporters for node {{ prometheus_client_fqdn }}
  set_fact:
    prometheus_additional_exporters: '{{ hostvars[prometheus_client_fqdn].prometheus_additional_exporters | default ({}) }}'

- name: Include task to setup tgroup for node {{ prometheus_client_fqdn }} exporters
  include_tasks: _setup_server_node_exporters_tgroup.yml
  loop_control:
    loop_var: prometheus_software_name
  with_items: '{{ hostvars[prometheus_client_fqdn].prometheus_components }}'
  when: "'prometheus_components' in hostvars[prometheus_client_fqdn]"

- name: Setup additional exporters for node {{ prometheus_client_fqdn }}
  include_tasks: _install_additional_exporters.yml
  when: prometheus_additional_exporters | length > 0

- name: Unset additional exporters variables
  set_fact:
    prometheus_additional_exporters: {}
