---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting nvidia_exporter (BugRoger) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_allow_build_test: true
    prometheus_software_author: BugRoger
    prometheus_software_binary_name: nvidia-exporter
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_officialname: nvidia-exporter
    prometheus_software_name: nvidia_exporter_bugroger
    prometheus_software_description: 'Prometheus nvidia_exporter (BugRoger), exporter of NVIDIA GPU metrics'
    prometheus_software_documentation: 'https://github.com/BugRoger/nvidia-exporter'
    prometheus_software_service_test: '{{ prometheus_nvidia_exporter_bugroger_service_test | default(true) }}'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '-web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
