#!/bin/bash

EXIT=0

function check_for_file {
    if [ ! -f "$1" ] ; then
        echo "Test $1 is missing"
        EXIT=1
    fi
}

for f in $(ls tasks | grep -Ev '^(_|main.yml$|promcron|promrun|sssd_check|wip)' | sed 's/\.yml$//')
do
    check_for_file "tests/inspec/default/${f}.rb"
done

for s in $(grep -r text_collector_examples tasks/node_exporter.yml|sed -e "s/'//g" -e 's/"//g' -e 's/.*text_collector_examples\///g')
do
    check_for_file "tests/inspec/default/script_${s}.rb"
done

if [ "$EXIT" -eq "0" ] ; then
    echo "OK"
fi

exit $EXIT
