---
name: Release
on:
  workflow_run:
    workflows: [ kitchen, validate_ansible, validate_urls ]
    branches: [ master ]
    types: [ completed ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Only proceed if specified workflows succeeded
        uses: ahmadnassri/action-workflow-run-wait@v1

      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
